"""4

Revision ID: 222cb521980c
Revises: 77e113d19234
Create Date: 2025-02-05 13:18:19.543610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222cb521980c'
down_revision: Union[str, None] = '77e113d19234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task_data', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Task_data', 'User_data', ['user_id'], ['id'])
    op.drop_constraint('User_data_tasks_fkey', 'User_data', type_='foreignkey')
    op.drop_column('User_data', 'tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_data', sa.Column('tasks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('User_data_tasks_fkey', 'User_data', 'Task_data', ['tasks'], ['id'])
    op.drop_constraint(None, 'Task_data', type_='foreignkey')
    op.drop_column('Task_data', 'user_id')
    # ### end Alembic commands ###
