"""3

Revision ID: 77e113d19234
Revises: 978e14789195
Create Date: 2025-02-04 23:17:27.598749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e113d19234'
down_revision: Union[str, None] = '978e14789195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Task_data_name', table_name='Task_data')
    op.create_index(op.f('ix_Task_data_name'), 'Task_data', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Task_data_name'), table_name='Task_data')
    op.create_index('ix_Task_data_name', 'Task_data', ['name'], unique=False)
    # ### end Alembic commands ###
