"""2

Revision ID: 978e14789195
Revises: 3ab9546feb58
Create Date: 2025-02-04 23:13:34.911448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '978e14789195'
down_revision: Union[str, None] = '3ab9546feb58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task_data', sa.Column('discription', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Task_data', 'discription')
    # ### end Alembic commands ###
